DROP TABLE IF EXISTS nfl_vegas;
CREATE TABLE nfl_vegas (
	gameId char(40) not null,
	g_mnemonic varchar(75) not null,
	h_opening_line decimal(3,1),
	h_opening_ou decimal(3,1),
	h_bovada_line decimal(3,1),
	h_bovada_ou decimal(3,1),
	h_caesars_line decimal(3,1),
	h_caesars_ou decimal(3,1),
	h_westgate_line decimal(3,1),
	h_westgate_ou decimal(3,1),
	h_betonline_line decimal(3,1),
	h_betonline_ou decimal(3,1),
	h_mybookie_line decimal(3,1),
	h_mybookie_ou decimal(3,1),
	h_5dimes_line decimal(3,1),
	h_5dimes_ou decimal(3,1),
	h_topbet_line decimal(3,1),
	h_topbet_ou decimal(3,1),
	h_betdsi_line decimal(3,1),
	h_betdsi_ou decimal(3,1),
	h_gtbets_line decimal(3,1),
	h_gtbets_ou decimal(3,1),
	h_sportsbetting_line decimal(3,1),
	h_sportsbetting_ou decimal(3,1),
	h_sportbet_line decimal(3,1),
	h_sportbet_ou decimal(3,1),
	h_station_line decimal(3,1),
	h_station_ou decimal(3,1),
	h_mirage_line decimal(3,1),
	h_mirage_ou decimal(3,1),
	h_wynn_line decimal(3,1),
	h_wynn_ou decimal(3,1),
	h_avg_line decimal(3,1),
	h_avg_ou decimal(3,1),
	h_median_line decimal(3,1),
	h_median_ou decimal(3,1),
	h_high_line decimal(3,1),
	h_low_line decimal(3,1),
	h_high_ou decimal(3,1),
	h_low_ou decimal(3,1),
	primary key (gameId)
);


